/* Delete Extra Data */

delete from rachel_zoe_dbm_90_day where 
date like '' or 
date like'%Report Time:%'or
date like'%Date Range:%' or
date like'%Group By:%' or
date like'%Filter by Advertiser%' or
date like'%Filter by Partner%' or
date is null



/*Select Distinct Date*/
Select TO_DATE ("date", 'YYYY/MM/DD') as "Date"
,"advertiser"
,"advertiser id"
,"advertiser status"
,"advertiser integration code"
,"insertion order"
,"insertion order id"
,"insertion order status"
,"insertion order integration code"
,"line item"
,"line item id"
,"line item status"
,"line item integration code"
,"targeted data providers"
,"creative"
,"creative id"
,"dcm placement id"
,"creative status"
,"creative source"
,"creative integration code"
,"insertion order daily frequency"
,ISNULL(CONVERT(varchar(10),"line item daily frequency"),'') as "line item daily frequency"
,"line item lifetime frequency"
,"line item type"
,"app/url"
,"app/url id"
,"app/url excluded"
,"time to conversion (minutes)"
,"creative type"
,"ad position"
,"exchange"
,"exchange id"
,ISNULL(CONVERT(varchar(10),"dma code"),'') as "dma code"
,"dma name"
,"browser"
,"operating system"
,"isp or carrier"
,"environment"
,"inventory source"
,"inventory source id"
,"video player size"
,ISNULL(CONVERT(varchar(10),"max video duration (seconds)"),'') as "max video duration (seconds)"
,"mobile make"
,"mobile make and model"
,"device type"
,"advertiser currency"
,"impressions"
,"billable impressions"
,ISNULL(CONVERT(varchar(10),"invalid impressions"),'') as "invalid impressions"
,"active view: eligible impressions"
,"active view: measurable impressions"
,"active view: viewable impressions"
,"active view: not measurable impressions"
,"active view: not viewable impressions"
,"active view: average viewable time (seconds)"
,"active view: % measurable impressions"
,"active view: % viewable impressions"
,"active view: impression distribution (not measurable)"
,"active view: impression distribution (not viewable)"
,"active view: impression distribution (viewable)"
,"clicks"
,ISNULL(CONVERT(varchar(10),"invalid clicks"),'') as "invalid clicks"
,"total conversions"
,"post-click conversions"
,"post-view conversions"
,"revenue (adv currency)"
,"media cost (advertiser currency)"
,"total media cost (advertiser currency)"
,"dcm post-click revenue"
,"dcm post-view revenue"
,"data fees (adv currency)"
,"cpm fee 1 (adv currency)"
,"cpm fee 2 (adv currency)"
,"cpm fee 3 (adv currency)"
,"cpm fee 4 (adv currency)"
,"cpm fee 5 (adv currency)"
,"media fee 1 (adv currency)"
,"media fee 2 (adv currency)"
,"media fee 3 (adv currency)"
,"media fee 4 (adv currency)"
,"media fee 5 (adv currency)"
,"starts (video)"
,"first-quartile views (video)"
,"midpoint views (video)"
,"third-quartile views (video)"
,"complete views (video)"
,"completion rate (video)"
,"audio mutes (video)"
,"pauses (video)"
,"fullscreens (video)"
,"skips (video)"
,"video revenue ecpcv (adv currency)"
,"video media cost ecpcv (adv currency)"
,"total video media cost ecpcv (adv currency)"
,"companion impressions (video)"
,"companion clicks (video)"
,"backup images"
,"expansions"
,"interactive impressions"
,"average display time"
,"average interaction time"
,"_batch_id_"
,"_batch_last_run_" from rachel_zoe_dbm_recurring_02_10_17
Where date not in (Select distinct(date) from transform_data_1)